# Generated by Django 2.2.13 on 2020-06-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('DEF', ''), ('INT', 'Internationale Kueche'), ('ASI', 'Asiatische Kueche'), ('AFR', 'Afrikanische Kueche'), ('EUR', 'Europäische Kueche'), ('AME', 'Amerikanische Kueche'), ('SUA', 'Suedamerikanische Kueche')], default='DEF', max_length=30),
        ),
    ]
