# Generated by Django 2.2.13 on 2020-06-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_recipe_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='contained_allergen',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
