# Generated by Django 2.2.13 on 2020-06-12 01:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200612_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='contained_allergen',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NA', 'None'), ('nuts', 'Nuesse'), ('glut', 'Gluten'), ('lact', 'Kuhmilch'), ('fish', 'Fisch'), ('egg', 'Huehnereier')], max_length=26),
        ),
    ]
